---
- name:  Install our PGP key and add HTTPS support for APT
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7

- name: Install trans-https and ca-certs
  command: sudo apt-get install -y apt-transport-https ca-certificates

- name: Add our APT repository
  command: sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main > /etc/apt/sources.list.d/passenger.list'

- name: Updating
  apt: update_cache=yes

- name: Remove default config
  command: rm -rf /etc/nginx/sites-enabled/default

- name: pkg - install nginx passenger packages
  apt: pkg={{ item }} state=present
  with_items:
    - nginx-extras
    - passenger
  notify: nginx restart
