---
- name: Updating
  apt: update_cache=yes

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/iptables
  notify: restart iptables

- name: Install Node.js and NPM
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - npm
